components:
  - changed-files:
      - any-glob-to-any-file: packages/components/components/**/*

dependencies:
  - changed-files:
      - any-glob-to-any-file: yarn.lock

design.elvia.io:
  - changed-files:
      - any-glob-to-any-file:
          [
            'packages/web/**/*',
            '!packages/web/src/assets/changelogs/**/*',
            '!packages/web/src/assets/js/elvis.js',
          ]

elvis:
  - changed-files:
      - any-glob-to-any-file: packages/elvis/**/*

tokens:
  - changed-files:
      - any-glob-to-any-file: packages/elvis-*/**/*

ci/cd:
  - changed-files:
      - any-glob-to-any-file: [.github/workflows/**/*, .github/labels.yml]
