components:
  - packages/components/components/**/*

dependencies:
  - yarn.lock

design.elvia.io:
  - any:
      [
        'packages/web/**/*',
        '!packages/web/src/assets/changelogs/**/*',
        '!packages/web/src/assets/js/elvis.js',
      ]

elvis:
  - packages/elvis/**/*

tokens:
  - packages/elvis-*/**/*
