components:
  - packages/components/components/**/*

dependencies:
  - yarn.lock
  - package.json
  - */package.json

design.elvia.io:
  - packages/web/**/*

elvis:
  - packages/elvis/**/*

tokens:
  - packages/elvis-*/**/*
