compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - level: discard
    pattern: "@angular-eslint/* doesn't provide *"
  - level: discard
    pattern: "@nrwl/* doesn't provide *"
  - level: discard
    pattern: stylelint-selector-bem-pattern@* doesn't provide eslint

nodeLinker: node-modules

npmAuthToken: "${NODE_AUTH_TOKEN-''}"

yarnPath: .yarn/releases/yarn-4.0.0.cjs
