import * as fs from 'fs';
import * as gulp from 'gulp';
import * as typescript from 'gulp-typescript';
import * as del from 'del';
import { shadows } from './src/shadows';
import { lightTheme, lightThemeColors } from './src/themes/lightTheme';
import { darkTheme, darkThemeColors } from './src/themes/darkTheme';
import { BaseColors, Color, Theme, ThemeName } from './src/theme';

const WARNING = `// THIS FILE IS AUTOMATICALLY GENERATED AND WILL BE OVERWRITTEN.
// DO NOT MAKE CHANGES TO THIS FILE DIRECTLY.\n\n`;

const transpileElviaColors = async () => {
  const tsProject = typescript.createProject('../components/tsconfig.json');
  return gulp.src('./src/**/*.ts').pipe(tsProject()).pipe(gulp.dest('./dist/'));
};

function cleanup() {
  return del(['./dist/**/*'], { force: true });
}

const makeDistFolder = async () => {
  const dir = './dist';
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  return true;
};

const generateElviaColorsThemeVariablesScss = async () => {
  const rootVariables = {
    ...getBaseColors(lightThemeColors, 'light'),
    ...getBaseColors(darkThemeColors, 'dark'),
  };
  const lightVariables = getThemedCssVariables(lightTheme);
  const darkVariables = getThemedCssVariables(darkTheme);

  let fileContent = WARNING;

  fileContent += `:root {\n`;
  Object.entries(rootVariables).forEach(([name, color]) => (fileContent += `\t${name}: ${color};\n`));
  fileContent += `}\n`;
  fileContent += `.e-theme-light,\n:root {\n`;
  Object.entries(lightVariables).forEach(([name, color]) => (fileContent += `\t${name}: ${color};\n`));
  fileContent += `}\n`;
  fileContent += `.e-theme-light {\n\tbackground: var(--e-color-background-1);\n`;
  fileContent += `\tcolor: var(--e-color-text-1);\n}\n`;
  fileContent += `.e-theme-dark {\n`;
  Object.entries(darkVariables).forEach(([name, color]) => (fileContent += `\t${name}: ${color};\n`));
  fileContent += `\tbackground: var(--e-color-background-1);\n`;
  fileContent += `\tcolor: var(--e-color-text-1);\n`;
  fileContent += `}\n`;

  fs.writeFileSync('./dist/themeVariables.scss', fileContent);
  return true;
};

const getBaseColors = (colors: BaseColors, theme: ThemeName): Record<string, string> => {
  const variables: Record<string, string> = {};
  Object.values(colors).forEach((category) =>
    Object.keys(category).forEach(
      (color) => (variables[`--e-theme-${theme}-${color}`] = category[color].color),
    ),
  );
  return variables;
};

const getThemedCssVariables = (theme: Theme) => {
  const variables: Record<string, string> = {};
  Object.values(theme).forEach((category: Record<string, Color>) =>
    Object.entries(category).forEach(([label, color]) => {
      variables[`--e-color-${label}`] = color.hex;
      if (color.contrast) {
        variables[`--e-color-${label}--contrast`] = color.contrast;
      }
    }),
  );
  return variables;
};

const generateElvisShadowMapScss = async () => {
  let fileContent = WARNING;
  fileContent += `$shadow: (\n`;
  Object.entries(shadows).forEach(([name, shadow]) => {
    fileContent += `\t'${name}': ${shadow.boxShadow},\n`;
  });
  fileContent += `);\n\n`;

  fs.writeFileSync('./dist/elvisShadowMap.scss', fileContent);
  return true;
};

gulp.task(
  'default',
  gulp.series(
    makeDistFolder,
    cleanup,
    generateElvisShadowMapScss,
    generateElviaColorsThemeVariablesScss,
    transpileElviaColors,
    function (done) {
      console.log('Elvis-colors - Successfully built Elvis-colors! ');
      done();
    },
  ),
);
