// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface ICenteredContentFields {
  /** Title */
  title?: string | undefined;

  /** Content */
  content: Document;
}

/** For centering content inside a section */

export interface ICenteredContent extends Entry<ICenteredContentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'centeredContent';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IDocumentationPageFields {
  /** Title */
  title: string;

  /** isMainPage */
  isMainPage?: boolean | undefined;

  /** Figma url */
  figmaUrl?: string | undefined;

  /** Page Description */
  pageDescription?: Document | undefined;

  /** Content */
  content?: Document | undefined;

  /** path */
  path: string;
}

/** All documentation pages should use this model and then be added to the correct subMenu */

export interface IDocumentationPage extends Entry<IDocumentationPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'documentationPage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IDownloadContentFields {
  /** Name */
  name: string;

  /** Display image */
  displayImage: Asset;

  /** Downloadable content */
  downloadableContent: Asset;
}

/** Upload files that will be displayed and downloadable */

export interface IDownloadContent extends Entry<IDownloadContentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'downloadContent';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IGridFields {
  /** Name */
  name?: string | undefined;

  /** Background */
  background: 'White' | 'Grey' | 'Dark';

  /** Grid elements */
  gridElements: (IDownloadContent | IImage)[];
}

export interface IGrid extends Entry<IGridFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'grid';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IImageFields {
  /** Name */
  name: string;

  /** Alt text */
  altText: string;

  /** Size */
  size: 'original' | '25%' | '50%' | '75%' | '100%';

  /** Alignment */
  alignment?: 'left' | 'right' | 'center' | undefined;

  /** Image */
  image: Asset;

  /** Description */
  description?: Document | undefined;

  /** Content next to image */
  inlineText?: Document | undefined;
}

export interface IImage extends Entry<IImageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'image';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IInternalLinkFields {
  /** Link text */
  title: string;

  /** Type */
  type: 'Standard' | 'Action';

  /** Url design.elvia.io (internal) */
  page?: IDocumentationPage | undefined;

  /** Name of paragraph on design.elvia.io */
  paragraph?: string | undefined;

  /** Url new tab / external */
  urlNewTab?: string | undefined;
}

/** Use for all links */

export interface IInternalLink extends Entry<IInternalLinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'internalLink';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILandingPageFields {
  /** Title */
  title: string;

  /** Overview image */
  overviewImage?: Asset | undefined;

  /** Description */
  description?: string | undefined;
}

/** Landing page should be wrapped inside a documentationPage and then be placed inside the subMenu it belongs to */

export interface ILandingPage extends Entry<ILandingPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'landingPage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILandingPageWithCardsFields {
  /** Title */
  title: string;

  /** Overview card */
  overviewCard: IOverviewCard[];
}

/** Landing page should be wrapped inside a documentationPage and then be placed inside the subMenu it belongs to */

export interface ILandingPageWithCards extends Entry<ILandingPageWithCardsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'landingPageWithCards';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IMainMenuFields {
  /** Title */
  title?: string | undefined;

  /** Submenus */
  submenus?: ISubMenu[] | undefined;
}

/** The main menu, contains submenus */

export interface IMainMenu extends Entry<IMainMenuFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'mainMenu';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IOverviewCardFields {
  /** Page icon */
  pageIcon: Asset;

  /** Title */
  title: string;

  /** Page url */
  pageUrl: IDocumentationPage;
}

/** Cards for navigating to content from overview pages */

export interface IOverviewCard extends Entry<IOverviewCardFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'overviewCard';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISectionFields {}

/** Section - should always be inside a documentationPage */

export interface ISection extends Entry<ISectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'section';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISubMenuFields {
  /** Title */
  title: string;

  /** landing-page */
  landingPage?: IDocumentationPage | undefined;

  /** Pages */
  pages?: IDocumentationPage[] | undefined;

  /** Path */
  path: string;
}

/** Sub menues are the elements in the header that contains all documentation pages. SubMenues should be added to the MainMenu */

export interface ISubMenu extends Entry<ISubMenuFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'subMenu';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISubsectionFields {}

/** Sub-section, should always be inside a section */

export interface ISubsection extends Entry<ISubsectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'subsection';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IWhenToUseFields {
  /** Name */
  name: string;

  /** When to use */
  whenToUse: Document;

  /** When not to use */
  whenNotToUse: Document;
}

/** Bullet lists of when and when not to use a component. */

export interface IWhenToUse extends Entry<IWhenToUseFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'whenToUse';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE =
  | 'centeredContent'
  | 'documentationPage'
  | 'downloadContent'
  | 'grid'
  | 'image'
  | 'internalLink'
  | 'landingPage'
  | 'landingPageWithCards'
  | 'mainMenu'
  | 'overviewCard'
  | 'section'
  | 'subMenu'
  | 'subsection'
  | 'whenToUse';

export type LOCALE_CODE = 'en-GB' | 'nb-NO';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-GB';
