/*
for renaming/deprecating icons add the following:
- deprecated: 'version number' e.g 4.6.0
- newIconName : reference to new icon to be displayed

example:
    { name: 'add_circle', deprecated: '4.6.0', newIconName: 'add_circle_new' },
*/
module.exports = [
  { name: 'add_circle', terms: ['plus', '+', 'maximize', 'expand', 'create'], thirdparty: ['streamline'] },
  { name: 'add_circle-color', terms: ['plus', '+', 'maximize', 'expand', 'create'] },
  { name: 'add_circle-filled', terms: ['plus', '+', 'maximize', 'expand', 'create'] },
  { name: 'add_circle-filled-color', terms: ['plus', '+', 'maximize', 'expand', 'create'] },
  { name: 'add_powermeter', terms: [], thirdparty: ['streamline'] },
  { name: 'add_powermeter-color', terms: [] },
  { name: 'agreements-color', terms: [], thirdparty: ['streamline'] },
  { name: 'analytics_bars', terms: ['data', 'effect', 'board', 'wave', 'measure'], thirdparty: ['streamline'] },
  { name: 'arrow_circle-color', deprecated: '4.7.0', newIconName: 'arrow_right_circle-color' },
  { name: 'arrow_right_circle-color', terms: ['next', 'forward'] },
  { name: 'arrow_circle-filled-color', deprecated: '4.7.0', newIconName: 'arrow_right_circle-filled-color' },
  { name: 'arrow_right_circle-filled-color', terms: ['next', 'forward'] },
  { name: 'arrow_right_circle', terms: ['long', 'next', 'forward'], thirdparty: ['streamline'] },
  { name: 'arrow_left_circle', terms: ['long', 'back', 'previous', 'backward'], thirdparty: ['streamline'] },
  { name: 'arrow_left_circle-color', terms: ['back', 'backward', 'previous'] },
  { name: 'arrow_left_circle-filled-color', terms: ['back', 'backward', 'previous'] },
  { name: 'arrow_down', terms: ['expand', 'open'], thirdparty: ['streamline'] },
  { name: 'arrow_down-bold', terms: ['expand', 'open'] },
  { name: 'arrow_external', terms: ['link'], thirdparty: ['streamline'] },
  { name: 'arrow_external-bold', terms: ['link'] },
  { name: 'arrow_left', terms: [], thirdparty: ['streamline'] },
  { name: 'arrow_left-bold', terms: [] },
  { name: 'arrow_long_left', terms: ['back', 'backward', 'previous'], thirdparty: ['streamline'] },
  { name: 'arrow_long_left-bold', terms: ['back', 'backward', 'previous'] },
  { name: 'arrow_long_right', terms: ['next', 'forward'], thirdparty: ['streamline'] },
  { name: 'arrow_long', deprecated: '6.2.0', newIconName: 'arrow_long_right' },
  { name: 'arrow_long_right-bold', terms: ['next', 'forward'] },
  { name: 'arrow_long-bold', deprecated: '6.2.0', newIconName: 'arrow_long_right-bold' },
  { name: 'arrow_right', terms: ['open'], thirdparty: ['streamline'] },
  { name: 'arrow_right-bold', terms: ['open'] },
  { name: 'arrow_up', terms: ['collapse', 'close'], thirdparty: ['streamline'] },
  { name: 'arrow_up-bold', terms: ['collapse', 'close'] },
  { name: 'attachment-color', terms: [], thirdparty: ['streamline'] },
  { name: 'bin', terms: ['delete', 'trash'], thirdparty: ['streamline'] },
  { name: 'bookmark', terms: [], thirdparty: ['streamline'] },
  { name: 'bookmark-filled', terms: [] },
  { name: 'business-color', terms: [], thirdparty: ['streamline'] },
  { name: 'cabin', terms: ['cottage', 'house', 'outside', 'woods'], thirdparty: ['streamline'] },
  { name: 'calendar', terms: [], thirdparty: ['streamline'] },
  { name: 'calendar_clock-color', terms: [], thirdparty: ['streamline'] },
  { name: 'calendar-color', terms: [] },
  { name: 'call', terms: ['phone', 'mobile', 'telephone'], thirdparty: ['streamline'] },
  { name: 'car_charger-color', terms: [], thirdparty: ['streamline'] },
  { name: 'chat', terms: ['message', 'text', 'write', 'conversation'], thirdparty: ['streamline'] },
  { name: 'charging_battery', terms: ['charge', 'load'] },
  { name: 'charging_battery-color', terms: ['charge', 'power'] },
  { name: 'check', terms: [], thirdparty: ['streamline'] },
  { name: 'check-bold', terms: [] },
  { name: 'check_circle', terms: [], thirdparty: ['streamline'] },
  { name: 'check_circle-filled', terms: [] },
  { name: 'check_circle-filled-color', terms: [] },
  { name: 'check_shield', terms: ['guard', 'safe'], thirdparty: ['streamline'] },
  { name: 'checklist-color', terms: [], thirdparty: ['streamline'] },
  { name: 'clock', terms: [], thirdparty: ['streamline'] },
  { name: 'close', terms: ['x', 'remove'], thirdparty: ['streamline'] },
  { name: 'close-bold', terms: ['x', 'remove'] },
  { name: 'close_menu', terms: ['x', 'remove'], thirdparty: ['streamline'] },
  { name: 'cog', terms: ['settings', 'gear'], thirdparty: ['streamline'] },
  { name: 'cookie', terms: ['cookies'], thirdparty: ['streamline'] },
  { name: 'cost_cut-color', terms: [], thirdparty: ['streamline'] },
  { name: 'collapse_circle-color', terms: [], thirdparty: ['streamline'] },
  { name: 'collapse_circle-filled-color', terms: [] },
  { name: 'copy', terms: [], thirdparty: ['streamline'] },
  { name: 'crane', terms: ['hook', 'building', 'tower'], thirdparty: ['streamline'] },
  { name: 'credit_card', terms: [], thirdparty: ['streamline'] },
  { name: 'cut_electricity_pillar', terms: [], thirdparty: ['streamline'] },
  { name: 'cut_electricity_pillar-color', terms: [] },
  { name: 'danger_electricity-color', terms: [], thirdparty: ['streamline'] },
  { name: 'dashboard', terms: [], thirdparty: ['streamline'] },
  { name: 'dashboard-color', terms: [] },
  { name: 'design_process-color', terms: [], thirdparty: ['streamline'] },
  { name: 'digging-color', terms: [], thirdparty: ['streamline'] },
  { name: 'download', terms: [], thirdparty: ['streamline'] },
  { name: 'drag_handle', terms: ['drop', 'grab', 'sort', 'move'], thirdparty: ['streamline'] },
  { name: 'edit', terms: ['pencil', 'pen'], thirdparty: ['streamline'] },
  { name: 'electric_cabinet', terms: [], thirdparty: ['streamline'] },
  { name: 'electric_cabinet-color', terms: [] },
  { name: 'electric_car-color', terms: [], thirdparty: ['streamline'] },
  { name: 'electric_home', terms: [], thirdparty: ['streamline'] },
  { name: 'electric_home-color', terms: [] },
  { name: 'electrical_system', terms: [], thirdparty: ['streamline'] },
  { name: 'electrical_system-color', terms: [] },
  { name: 'electricity_pillar', terms: [], thirdparty: ['streamline'] },
  { name: 'electricity_safety', terms: [], thirdparty: ['streamline'] },
  { name: 'electricity_safety-color', terms: [] },
  { name: 'electricity_tower', terms: ['energy', 'high tension', 'tower', 'power'], thirdparty: ['streamline'] },
  { name: 'elsmart-color', terms: [], thirdparty: ['streamline'] },
  { name: 'expand_circle-color', terms: [], thirdparty: ['streamline'] },
  { name: 'expand_circle-filled-color', terms: [] },
  { name: 'filter', terms: [], thirdparty: ['streamline'] },
  { name: 'filter-filled', terms: [] },
  { name: 'flag', terms: [], thirdparty: ['streamline'] },
  { name: 'flag-bold', terms: [] },
  { name: 'flag-bold-color', terms: [] },
  { name: 'flag-color', terms: [] },
  { name: 'folder', terms: [], thirdparty: ['streamline'] },
  { name: 'folder_create', terms: ['add'], thirdparty: ['streamline'] },
  { name: 'folder_open', terms: [], thirdparty: ['streamline'] },
  { name: 'form_check-color', terms: [], thirdparty: ['streamline'] },
  { name: 'form', terms: ['application', 'paper', 'sheet', 'letter', 'document', 'write', 'edit'], thirdparty: ['streamline'] },
  { name: 'form-color', terms: [] },
  { name: 'full_battery', terms: [], thirdparty: ['streamline'] },
  { name: 'full_battery-color', terms: [] },
  { name: 'freshchat-color', terms: ['message', 'text', 'write'], thirdparty: ['streamline'] },
  { name: 'graph_bar', terms: [], thirdparty: ['streamline'] },
  { name: 'graph_bar-color', terms: [] },
  { name: 'graph_up', terms: ['chart', 'cost'], thirdparty: ['streamline'] },
  { name: 'ground_fault', terms: [], thirdparty: ['streamline'] },
  { name: 'ground_fault-color', terms: [] },
  { name: 'hammer_wrench-color', terms: [] },
  { name: 'han', terms: [], thirdparty: ['streamline'] },
  { name: 'han-color', terms: [] },
  { name: 'home', terms: [], thirdparty: ['streamline'] },
  { name: 'home-color', terms: [] },
  { name: 'house_rebuilding-color', terms: [], thirdparty: ['streamline'] },
  { name: 'image_add-color', terms: [], thirdparty: ['streamline'] },
  { name: 'information_circle', terms: ['help', 'advice', 'guidance'], thirdparty: ['streamline'] },
  { name: 'information_circle-color', terms: ['help', 'advice', 'guidance'] },
  { name: 'information_circle-filled-color', terms: ['help', 'advice', 'guidance'] },
  { name: 'installatorweb-color', terms: ['installatørweb', 'innstallatørweb'], thirdparty: ['streamline'] },
  { name: 'invoice-color', terms: [], thirdparty: ['streamline'] },
  { name: 'laptop-color', terms: ['computer', 'screen', 'pc', 'mac'] },
  { name: 'list', terms: [], thirdparty: ['streamline'] },
  { name: 'list_bullets-bold', terms: [], thirdparty: ['streamline'] },
  { name: 'loading', terms: [], thirdparty: ['streamline'] },
  { name: 'lock', terms: [], thirdparty: ['streamline'] },
  { name: 'lock_hierarchy', terms: ['lock', 'hierarchy', 'closed', 'nodes'], thirdparty: ['streamline'] },
  { name: 'logout', terms: [], thirdparty: ['streamline'] },
  { name: 'mail', terms: ['e-mail', 'post', 'letter', 'email'], thirdparty: ['streamline'] },
  { name: 'mail_error-color', terms: ['e-mail', 'post', 'letter', 'fail', 'wrong', 'email'], thirdparty: ['streamline'] },
  { name: 'mail_monitor-color', terms: ['observe'], thirdparty: ['streamline'] },
  { name: 'mail_send-color', terms: ['e-mail', 'post', 'letter', 'email'], thirdparty: ['streamline'] },
  { name: 'map_pin-color', terms: [], thirdparty: ['streamline'] },
  { name: 'menu', terms: [], thirdparty: ['streamline'] },
  { name: 'menu-bold', terms: [] },
  { name: 'minus', terms: ['subtract', 'minimize', 'collapse'], thirdparty: ['streamline'] },
  { name: 'minus-bold', terms: ['subtract', 'minimize', 'collapse'] },
  { name: 'money-color', terms: ['finance', 'cash', 'coins', 'payment', 'pay', 'cost'], thirdparty: ['streamline'] },
  { name: 'more_menu', terms: ['actions', 'contextual', 'kebab', 'dots'] },
  { name: 'move_circle', terms: ['move', 'transfer'], thirdparty: ['streamline'] },
  { name: 'move_truck-color', terms: [], thirdparty: ['streamline'] },
  { name: 'new_tab-bold', terms: ['external', 'open', 'link'], thirdparty: ['streamline'] },
  { name: 'note_approved-color', terms: [], thirdparty: ['streamline'] },
  { name: 'note_check-color', terms: [], thirdparty: ['streamline'] },
  { name: 'notification-bold', terms: ['alarm', 'bell', 'alert'], thirdparty: ['streamline'] },
  { name: 'open_menu', terms: [], thirdparty: ['streamline'] },
  { name: 'paper_plane', terms: ['send', 'message'], thirdparty: ['streamline'] },
  { name: 'pause_circle-color', terms: ['stop'], thirdparty: ['streamline'] },
  { name: 'pause_circle-filled-color', terms: ['stop'] },
  { name: 'phone', terms: ['mobile'], thirdparty: ['streamline'] },
  { name: 'phone_comment', terms: ['mobile'], thirdparty: ['streamline'] },
  { name: 'phone_comment-color', terms: ['mobile', 'write', 'text', 'message'] },
  { name: 'phone_image', terms: ['mobile', 'picture', 'content'], thirdparty: ['streamline'] },
  { name: 'pdf_document', terms: ['adobe', 'file'], thirdparty: ['streamline'] },
  { name: 'pie_chart', terms: [], thirdparty: ['streamline'] },
  { name: 'pin', terms: [], thirdparty: ['streamline'] },
  { name: 'pin-color', terms: ['place', 'location', 'locate', 'position', 'area', 'map'] },
  { name: 'pin-filled', terms: ['place', 'location', 'locate', 'position', 'area', 'map'] },
  { name: 'play_circle-color', terms: ['start', 'go'], thirdparty: ['streamline'] },
  { name: 'play_circle-filled-color', terms: ['start', 'go'] },
  { name: 'plus', terms: ['add', 'maximize', 'expand', 'create'], thirdparty: ['streamline'] },
  { name: 'plus-bold', terms: ['add', 'maximize', 'expand', 'create'] },
  { name: 'position-bold', terms: [], thirdparty: ['streamline'] },
  { name: 'position-bold-color', terms: [] },
  { name: 'position_off-bold', terms: [], thirdparty: ['streamline'] },
  { name: 'power', terms: [], thirdparty: ['streamline'] },
  { name: 'power_outage', terms: [], thirdparty: ['streamline'] },
  { name: 'power_outage-2', terms: [], thirdparty: ['streamline'] },
  { name: 'power_outage-2-color', terms: [] },
  { name: 'power_outage-color', terms: [] },
  { name: 'power_outage_map', terms: [], thirdparty: ['streamline'] },
  { name: 'power_outage-orange-color', terms: [] },
  { name: 'power_service', terms: ['electricity', 'warning', 'connect', 'disconnect', 'contact'], thirdparty: ['streamline'] },
  { name: 'power_service-color', terms: ['electricity', 'warning', 'connect', 'disconnect', 'contact'] },
  { name: 'power-color', terms: [] },
  { name: 'powerline', terms: [], thirdparty: ['streamline'] },
  { name: 'powerline-color', terms: [] },
  { name: 'powermeter_ams', terms: [], thirdparty: ['streamline'] },
  { name: 'powermeter_ams-color', terms: [] },
  { name: 'powermeter_old', terms: [] },
  { name: 'powermeter-color', terms: [], thirdparty: ['streamline'] },
  { name: 'profile', terms: [], thirdparty: ['streamline'] },
  { name: 'profile-2', terms: [] },
  { name: 'profile-2-color', terms: [] },
  { name: 'profile-bold', terms: [] },
  { name: 'question_circle', terms: ['?', 'help', 'answer'], thirdparty: ['streamline'] },
  { name: 'question_circle-color', terms: ['?', 'help', 'answer'] },
  { name: 'question_circle-filled-color', terms: ['?', 'help', 'answer'] },
  { name: 'quotation-color', terms: ['quote', 'reference'], thirdparty: ['streamline'] },
  { name: 'refresh', terms: [], thirdparty: ['streamline'] },
  { name: 'remove_circle', terms: ['delete', 'dismiss', 'discard'], thirdparty: ['streamline'] },
  { name: 'remove_circle-color', terms: ['delete', 'dismiss', 'discard'] },
  { name: 'remove_circle-filled', terms: ['delete', 'dismiss', 'discard'] },
  { name: 'remove_circle-filled-color', terms: ['delete', 'dismiss', 'discard'] },
  { name: 'renewable_energy', terms: [], thirdparty: ['streamline'] },
  { name: 'renewable_energy-color', terms: [] },
  { name: 'reset', terms: [], thirdparty: ['streamline'] },
  { name: 'rss-bold', terms: ['feed', 'connection', 'internet', 'online'], thirdparty: ['streamline'] },
  { name: 'figma', terms: [] },
  { name: 'search', terms: ['find', 'navigation', 'explore', 'inspect', 'look'], thirdparty: ['streamline'] },
  { name: 'search-color', terms: ['find', 'navigation', 'explore', 'inspect', 'look'] },
  { name: 'search-bold', terms: ['find', 'navigation', 'explore', 'inspect', 'look'] },
  { name: 'search-bold-color', terms: ['find', 'navigation', 'explore', 'inspect', 'look'] },
  { name: 'smart_city', terms: [] },
  { name: 'smart_city-color', terms: [], thirdparty: ['streamline'] },
  { name: 'solar_panel', terms: [], thirdparty: ['streamline'] },
  { name: 'solar_panel-color', terms: [] },
  { name: 'sorting_ascending-bold', terms: ['sort', 'sorting', 'order', 'up'], thirdparty: ['streamline'] },
  { name: 'sorting_descending-bold', terms: ['sort', 'sorting', 'order', 'down'], thirdparty: ['streamline'] },
  { name: 'sorting-bold', terms: ['sort', 'sorting', 'order'], thirdparty: ['streamline'] },
  { name: 'star-filled', terms: ['favorite', 'favourite'] },
  { name: 'star', terms: ['favorite', 'favourite'], thirdparty: ['streamline'] },
  { name: 'step_1', terms: ['number', 'first', 'one'], thirdparty: ['streamline'] },
  { name: 'step_2', terms: ['number', 'second', 'two'], thirdparty: ['streamline'] },
  { name: 'step_3', terms: ['number', 'third', 'three'], thirdparty: ['streamline'] },
  { name: 'step_4', terms: ['number', 'fourth', 'four'], thirdparty: ['streamline'] },
  { name: 'step_5', terms: ['number', 'fifth', 'five'], thirdparty: ['streamline'] },
  { name: 'subtract_circle', terms: ['minus', '-', 'minimize', 'collapse'], thirdparty: ['streamline'] },
  { name: 'subtract_circle-filled', terms: ['minus', '-', 'minimize', 'collapse'] },
  { name: 'subtract_circle-filled-color', terms: ['minus', '-', 'minimize', 'collapse'] },
  { name: 'support', terms: ['customer service', 'help'], thirdparty: ['streamline'] },
  { name: 'sync', terms: ['synchronization', 'refresh', 'reload', 'arrows'], thirdparty: ['streamline'] },
  { name: 'tag_add', terms: [], thirdparty: ['streamline'] },
  { name: 'tag', terms: [], thirdparty: ['streamline'] },
  { name: 'thumbnail', terms: [], thirdparty: ['streamline'] },
  { name: 'touch_finger-color', terms: [], thirdparty: ['streamline'] },
  { name: 'tree_falling', terms: [], thirdparty: ['streamline'] },
  { name: 'tree_powerline', terms: [], thirdparty: ['streamline'] },
  { name: 'tree_powerline-color', terms: [] },
  { name: 'unlock', terms: [], thirdparty: ['streamline'] },
  { name: 'upload', terms: [], thirdparty: ['streamline'] },
  { name: 'user_testing-color', terms: [], thirdparty: ['streamline'] },
  { name: 'users', terms: ['profile', 'persons', 'people', 'group', 'multiple'], thirdparty: ['streamline'] },
  { name: 'view_off', terms: ['eye', 'eye closed'], thirdparty: ['streamline'] },
  { name: 'view_on', terms: ['eye', 'eye open'], thirdparty: ['streamline'] },
  { name: 'warning_circle', terms: ['!', 'danger', 'alert', 'caution', 'exclamation'], thirdparty: ['streamline'] },
  { name: 'warning_circle-filled', terms: ['!', 'danger', 'alert', 'caution', 'exclamation'] },
  { name: 'warning_electricity-color', terms: ['!', 'danger', 'alert', 'caution', 'exclamation'], thirdparty: ['streamline'] },
  { name: 'warning_triangle', terms: ['!', 'danger', 'alert', 'caution', 'exclamation'], thirdparty: ['streamline'] },
  { name: 'warning_circle-filled-color', terms: ['!', 'danger', 'alert', 'caution', 'exclamation'] },
  { name: 'web_library-color', terms: [], thirdparty: ['streamline'] },
  { name: 'work_under_line-color', terms: [], thirdparty: ['streamline'] },
  { name: 'worker-color', terms: [], thirdparty: ['streamline'] },
  { name: 'wrench', terms: ['working', 'in progress', 'tool'], thirdparty: ['streamline'] },
  { name: 'zoom_in', terms: [], thirdparty: ['streamline'] },
  { name: 'zoom_out', terms: [], thirdparty: ['streamline'] },
];
