module.exports = [
  {
    name: 'title-lg',
    properties: [
      { key: 'family', value: 'Red Hat Display' },
      { key: 'size', value: '44px' },
      { key: 'size-m', value: '32px' },
      { key: 'weight', value: '900' },
      { key: 'height', value: '53px' },
      { key: 'height-m', value: '34px' },
      { key: 'letter-spacing', value: 'unset' },
      { key: 'style', value: 'unset' },
      { key: 'transform', value: 'unset' },
      { key: 'color', value: '#000' },
    ],
  },
  {
    name: 'title-md',
    properties: [
      { key: 'family', value: 'Red Hat Display' },
      { key: 'size', value: '30px' },
      { key: 'size-m', value: '24px' },
      { key: 'weight', value: '700' },
      { key: 'height', value: '36px' },
      { key: 'height-m', value: '29px' },
      { key: 'letter-spacing', value: 'unset' },
      { key: 'style', value: 'unset' },
      { key: 'transform', value: 'unset' },
      { key: 'color', value: '#000' },
    ],
  },
  {
    name: 'title-sm',
    properties: [
      { key: 'family', value: 'Red Hat Display' },
      { key: 'size', value: '24px' },
      { key: 'size-m', value: '20px' },
      { key: 'weight', value: '700' },
      { key: 'height', value: '29px' },
      { key: 'height-m', value: '24px' },
      { key: 'letter-spacing', value: 'unset' },
      { key: 'style', value: 'unset' },
      { key: 'transform', value: 'unset' },
      { key: 'color', value: '#000' },
    ],
  },
  {
    name: 'title-xs',
    properties: [
      { key: 'family', value: 'Red Hat Display' },
      { key: 'size', value: '18px' },
      { key: 'weight', value: '700' },
      { key: 'height', value: '22px' },
      { key: 'letter-spacing', value: 'unset' },
      { key: 'style', value: 'unset' },
      { key: 'transform', value: 'unset' },
      { key: 'color', value: '#000' },
    ],
  },
  {
    name: 'text-lead',
    properties: [
      { key: 'family', value: 'Red Hat Text' },
      { key: 'size', value: '24px' },
      { key: 'size-m', value: '22px' },
      { key: 'weight', value: '400' },
      { key: 'height', value: '39px' },
      { key: 'height-m', value: '36px' },
      { key: 'letter-spacing', value: 'unset' },
      { key: 'style', value: 'unset' },
      { key: 'transform', value: 'unset' },
      { key: 'color', value: '#000' },
    ],
  },
  {
    name: 'text-quote',
    properties: [
      { key: 'family', value: 'Red Hat Text' },
      { key: 'size', value: '26px' },
      { key: 'size-m', value: '20px' },
      { key: 'weight', value: '400' },
      { key: 'height', value: '42px' },
      { key: 'height-m', value: '32px' },
      { key: 'letter-spacing', value: 'unset' },
      { key: 'style', value: 'italic' },
      { key: 'transform', value: 'unset' },
      { key: 'color', value: '#000' },
    ],
  },
  {
    name: 'text-lg',
    altLabels: ['text-body'],
    properties: [
      { key: 'family', value: 'Red Hat Text' },
      { key: 'size', value: '20px' },
      { key: 'size-m', value: '18px' },
      { key: 'weight', value: '400' },
      { key: 'height', value: '32px' },
      { key: 'height-m', value: '29px' },
      { key: 'letter-spacing', value: 'unset' },
      { key: 'style', value: 'unset' },
      { key: 'transform', value: 'unset' },
      { key: 'color', value: '#000' },
    ],
  },
  {
    name: 'text-img',
    properties: [
      { key: 'family', value: 'Red Hat Text' },
      { key: 'size', value: '18px' },
      { key: 'size-m', value: '16px' },
      { key: 'weight', value: '400' },
      { key: 'align', value: 'center' },
      { key: 'height', value: '29px' },
      { key: 'height-m', value: '26px' },
      { key: 'letter-spacing', value: 'unset' },
      { key: 'style', value: 'italic' },
      { key: 'transform', value: 'unset' },
      { key: 'color', value: '#000' },
    ],
  },
  {
    name: 'text-md',
    altLabels: ['text-description'],
    properties: [
      { key: 'family', value: 'Red Hat Text' },
      { key: 'size', value: '16px' },
      { key: 'weight', value: '400' },
      { key: 'height', value: '28px' },
      { key: 'letter-spacing', value: 'unset' },
      { key: 'style', value: 'unset' },
      { key: 'transform', value: 'unset' },
      { key: 'color', value: '#000' },
    ],
  },
  {
    name: 'text-caps',
    properties: [
      { key: 'family', value: 'Red Hat Text' },
      { key: 'size', value: '14px' },
      { key: 'weight', value: '500' },
      { key: 'height', value: '17px' },
      { key: 'letter-spacing', value: '0.8px' },
      { key: 'style', value: 'unset' },
      { key: 'transform', value: 'uppercase' },
      { key: 'color', value: '#000' },
    ],
  },
  {
    name: 'text-sm',
    altLabels: ['text-info'],
    properties: [
      { key: 'family', value: 'Red Hat Text' },
      { key: 'size', value: '14px' },
      { key: 'weight', value: '400' },
      { key: 'height', value: '22px' },
      { key: 'letter-spacing', value: 'unset' },
      { key: 'style', value: 'unset' },
      { key: 'transform', value: 'unset' },
      { key: 'color', value: '#000' },
    ],
  },
  {
    name: 'text-label',
    properties: [
      { key: 'family', value: 'Red Hat Text' },
      { key: 'size', value: '16px' },
      { key: 'weight', value: '500' },
      { key: 'height', value: '23px' },
      { key: 'letter-spacing', value: 'unset' },
      { key: 'style', value: 'unset' },
      { key: 'transform', value: 'unset' },
      { key: 'color', value: '#000' },
    ],
  },
  {
    name: 'text-option',
    properties: [
      { key: 'family', value: 'Red Hat Text' },
      { key: 'size', value: '16px' },
      { key: 'weight', value: '400' },
      { key: 'height', value: '22px' },
      { key: 'letter-spacing', value: 'unset' },
      { key: 'style', value: 'unset' },
      { key: 'transform', value: 'unset' },
      { key: 'color', value: '#000' },
    ],
  },
];
