export enum Pages {
  // Home
  Index = '',
  Home = 'home',

  // Component Pages
  ComponentsStart = 'components',
  OverviewComp = 'overview-comp',
  Accordion = 'accordion',
  Alert = 'alert-messages',
  Autocomplete = 'autocomplete',
  Button = 'button',
  Breadcrumb = 'breadcrumb',
  Box = 'box',
  Card = 'card',
  Carousel = 'carousel',
  Chip = 'chip',
  Checkbox = 'checkbox',
  ContentLoader = 'content-loader',
  Divider = 'divider',
  Dropdown = 'dropdown',
  Toggle = 'toggle',
  Timepicker = 'timepicker',
  Datepicker = 'datepicker',
  DragAndDrop = 'draganddrop',
  FileUpload = 'fileUpload',
  RadioFilter = 'radio-filter',
  Header = 'header',
  Input = 'input',
  Label = 'label',
  Link = 'link',
  List = 'list',
  Modal = 'modal',
  Pagination = 'pagination',
  Popover = 'popover',
  PositionPicker = 'position-picker',
  Progressbar = 'progressbar',
  Radiobutton = 'radiobutton',
  SegmentedControl = 'segmented-control',
  Search = 'search',
  Select = 'select',
  Stepper = 'stepper',
  Table = 'table',
  Tabs = 'tabs',
  Tooltip = 'tooltip',

  // Pages not from CMS
  TheDesignSystem = 'the-design-system',
  NewProject = 'new-project',
  GetStartedDesigners = 'get-started-designers',
  Border = 'border',
  Color = 'color',
  Icon = 'icon',
  ToneOfVoice = 'tone-of-voice',
  Typography = 'typography',
  Shadow = 'shadow',
  Spacing = 'spacing',
  Grid = 'grid',
  Logo = 'logo',
  TheConcept = 'the-concept',
  Accessibility = 'accessibility',
  DesignProcess = 'design-process',
  UserFeedback = 'user-feedback',
  Utilities = 'utilities',
  Patterns = 'patterns',
  Contact = 'contact',
  Contribute = 'contribute',
  Faq = 'faq',
  Changelog = 'changelog',

  // Dev
  DevelopmentStart = 'dev',
  DevelopmentPlayground = 'playground',
}
