export enum Pages {
  // Home
  Index = '',
  Home = 'home',

  // Component Pages
  ComponentsStart = 'components',
  OverviewComp = 'overview-comp',
  Accordion = 'accordion',
  Alert = 'alert',
  Autocomplete = 'autocomplete',
  Button = 'button',
  Breadcrumb = 'breadcrumb',
  Box = 'box',
  Card = 'card',
  Carousel = 'carousel',
  Chip = 'chip',
  Checkbox = 'checkbox',
  ContentLoader = 'content-loader',
  Divider = 'divider',
  Dropdown = 'dropdown',
  Toggle = 'toggle',
  Timepicker = 'time-picker',
  Datepicker = 'datepicker',
  DatepickerRange = 'datepicker-range',
  DragAndDrop = 'drag-and-drop',
  FileUpload = 'file-upload',
  RadioFilter = 'radio-filter',
  Header = 'header',
  Input = 'input',
  Tag = 'tag',
  Link = 'link',
  List = 'list',
  Modal = 'modal',
  Pagination = 'pagination',
  Popover = 'popover',
  PositionPicker = 'position-picker',
  Progressbar = 'progressbar',
  Radiobutton = 'radiobutton',
  SegmentedControl = 'segmented-control',
  Search = 'search',
  Spotlight = 'spotlight',
  Stepper = 'stepper',
  Table = 'table',
  Tabs = 'tabs',
  Tooltip = 'tooltip',

  // Pages not from CMS
  TheDesignSystem = 'the-design-system',
  Color = 'color',
  Icon = 'icon',
  Typography = 'typography',
  Utilities = 'utility-classes',
  Contact = 'contact',
  Contribute = 'contribute',
  Faq = 'faq',
  Changelog = 'changelog',
  Shadow = 'shadow',

  // Dev
  DevelopmentStart = 'dev',
  DevelopmentPlayground = 'playground',
}
