export enum DocPageStatus {
  Coming = 'Coming',
  Done = 'Done',
  Ignore = 'Ignore',
  Progress = 'In progress',
}

export enum Pages {
  // Home
  Index = '',
  Home = 'home',

  // Component Pages
  Accordion = 'accordion',
  AccordionGroup = 'accordion-group',
  Alert = 'alert',
  Autocomplete = 'autocomplete',
  Badge = 'badge',
  Box = 'box',
  Breadcrumb = 'breadcrumb',
  Button = 'button',
  Card = 'card',
  Carousel = 'carousel',
  Checkbox = 'checkbox',
  Chip = 'chip',
  ComponentsStart = 'components',
  ContentLoader = 'content-loader',
  ContextMenu = 'context-menu',
  Datepicker = 'datepicker',
  DatepickerRange = 'datepicker-range',
  Divider = 'divider',
  DragAndDrop = 'drag-and-drop',
  Dropdown = 'dropdown',
  FileUpload = 'file-upload',
  Header = 'header',
  Input = 'input',
  Link = 'link',
  List = 'list',
  Modal = 'modal',
  OverviewComp = 'overview-comp',
  Pagination = 'pagination',
  Popover = 'popover',
  PositionPicker = 'position-picker',
  Progressbar = 'progressbar',
  RadioFilter = 'radio-filter',
  Radiobutton = 'radiobutton',
  Search = 'search',
  SegmentedControl = 'segmented-control',
  Slider = 'slider',
  Spotlight = 'spotlight',
  Stepper = 'stepper',
  Table = 'table',
  Tabs = 'tabs',
  Tag = 'tag',
  Thumbnail = 'thumbnail',
  Timepicker = 'timepicker',
  Toggle = 'toggle',
  Tooltip = 'tooltip',

  // Pages not from CMS
  Changelog = 'changelog',
  Color = 'color',
  Contact = 'contact',
  Contribute = 'contribute',
  Faq = 'faq',
  Icon = 'icon',
  Shadow = 'shadow',
  TheDesignSystem = 'the-design-system',
  Typography = 'typography',
  Utilities = 'utility-classes',

  // Dev
  DevelopmentPlayground = 'playground',
  DevelopmentStart = 'dev',
}
