export enum Pages {
    Home = 'home',
    Badge = 'badge-doc',
    Button = 'button-doc',
    Card = 'card-doc',
    Divider = 'divider-doc',
    Dropdown = 'dropdown-doc',
    Feedback = 'feedback-doc',
    Header = 'header-doc',
    Link = 'link-doc',
    Table = 'table-doc',
    Tags = 'tags-doc',
    Tooltip = 'tooltip-doc',
    Color = 'color-doc',
    Icon = 'icon-doc',
    Typography = 'typography-doc',
    Checkbox = 'checkbox-doc',
    CheckboxToggle = 'checkbox-toggle-doc',
    Input = 'input-doc',
    Radiobutton = 'radiobutton-doc',
    Select = 'select-doc',
    Shadow = 'shadow-doc',
    Notification = 'notification-dot-doc',
    Overview = 'overview-doc',
    OverviewUtil = 'overview-util-doc'
}
