export enum Pages {
    Home = 'home',
    Badge = 'badge-doc',
    Button = 'button-doc',
    Card = 'card-doc',
    Divider = 'divider-doc',
    Dropdown = 'dropdown-doc',
    Feedback = 'feedback-doc',
    Header = 'header-doc',
    Link = 'link-doc',
    Table = 'table-doc',
    Tags = 'tags-doc',
    Tooltip = 'tooltip-doc',
    Color = 'color-doc',
    Icon = 'icon-doc',
    Typography = 'typography-doc',
    Checkbox = 'checkbox-doc',
    CheckboxToggle = 'checkbox-toggle-doc',
    Input = 'input-doc',
    Radiobutton = 'radiobutton-doc',
    Select = 'select-doc',
    Shadow = 'shadow-doc',
    Notification = 'notification-dot-doc',
    OverviewComp = 'overview-comp-doc',
    OverviewUtil = 'overview-util-doc',
    NewProject = 'new-project-doc',
    Contribute = 'contribute-doc',

    Spacing = 'spacing-doc',
    Border = 'border-doc',
    Template = 'template-doc',

    // Accessibility Pages
    AccessibilityStart = 'accessibility',
    // children
    OverviewAccess = 'overview-accessibility-doc',
    Accessibility = 'accessibility-doc',
    AltText = 'alttext-doc',
    UUTools = 'uutools-doc',
}
