import { Color } from './color.interface';

export const primaryColors: Color[] = [
  {
    title: 'white',
    labels: ['elvia-on'],
    hex: '#FFFFFF',
    rgba: '255 / 255 / 255',
    contrastBlack: 'AAA',
    contrastWhite: '',
    lg: true,
  },
  {
    title: 'green',
    labels: ['elvia-charge'],
    hex: '#29D305',
    rgba: '41 / 211 / 5',
    contrastBlack: 'AAA',
    contrastWhite: '',
    lg: true,
  },
  {
    title: 'black',
    labels: ['elvia-off', 'font-color'],
    hex: '#000000',
    rgba: '0 / 0 / 0',
    contrastWhite: 'AAA',
    contrastBlack: '',
    lg: true,
  },
  {
    title: 'grey',
    hex: '#262626',
    rgba: '38 / 38 / 38',
    contrastWhite: 'AAA',
    contrastBlack: '',
    lg: true,
  },
];
export const signalColors: Color[] = [
  {
    title: 'yellow',
    hex: '#FFFF00',
    rgba: '255 / 255 / 0',
    contrastBlack: 'AAA',
    contrastWhite: '',
  },
  {
    title: 'orange',
    hex: '#FFA000',
    rgba: '255 / 160 / 0',
    contrastBlack: 'AAA',
    contrastWhite: '',
  },
  {
    title: 'red',
    hex: '#EE0701',
    rgba: '238 / 7 / 1',
    contrastBlack: 'AA',
    contrastWhite: 'AA',
  },
];
export const dataColors: Color[] = [
  {
    title: 'green-apple',
    titleWithSpace: 'green apple',
    hex: '#21AC04',
    rgba: '33 / 172 / 4',
    contrastBlack: 'AA',
    contrastWhite: '',
  },
  {
    title: 'violet-grape',
    titleWithSpace: 'violet grape',
    hex: '#490192',
    rgba: '73 / 1 / 146',
    contrastWhite: 'AAA',
    contrastBlack: '',
  },
  {
    title: 'blue-berry',
    titleWithSpace: 'blue berry',
    hex: '#006DDB',
    rgba: '0 / 109 / 219',
    contrastWhite: 'AA',
    contrastBlack: '',
  },
  {
    title: 'purple-plum',
    titleWithSpace: 'purple plum',
    hex: '#B66DFF',
    rgba: '182 / 109 / 255',
    contrastBlack: 'AA',
    contrastWhite: '',
  },
  {
    title: 'orange-mango',
    titleWithSpace: 'orange mango',
    hex: '#DB6D00',
    rgba: '219 / 109 / 0',
    contrastBlack: 'AA',
    contrastWhite: '',
  },
  {
    title: 'red-tomato',
    titleWithSpace: 'red tomato',
    hex: '#B90202',
    rgba: '185 / 2 / 2',
    contrastWhite: 'AAA',
    contrastBlack: '',
  },
];
export const greysColors: Color[] = [
  {
    title: 'grey-02',
    hex: '#FAFAFA',
    rgba: '38/38/38/0.02',
    contrastBlack: 'AAA',
    contrastWhite: '',
  },
  {
    title: 'grey-05',
    hex: '#F4F4F4',
    rgba: '38/38/38/0.05',
    contrastBlack: 'AAA',
    contrastWhite: '',
    labels: ['disabled-light'],
  },
  {
    title: 'grey-10',
    hex: '#E9E9E9',
    rgba: '38/38/38/0.1',
    contrastBlack: 'AAA',
    contrastWhite: '',
  },
  {
    title: 'grey-20',
    hex: '#D3D3D3',
    rgba: '38/38/38/0.2',
    contrastBlack: 'AAA',
    contrastWhite: '',
  },
  {
    title: 'grey-30',
    hex: '#BDBDBD',
    rgba: '38/38/38/0.3',
    contrastBlack: 'AAA',
    contrastWhite: '',
    labels: ['disabled'],
  },
  {
    title: 'grey-40',
    hex: '#A8A8A8',
    rgba: '38/38/38/0.4',
    contrastBlack: 'AAA',
    contrastWhite: '',
  },
  {
    title: 'grey-50',
    hex: '#929292',
    rgba: '38/38/38/0.5',
    contrastBlack: 'AA',
    contrastWhite: '',
  },
  {
    title: 'grey-60',
    hex: '#7C7C7C',
    rgba: '38/38/38/0.6',
    contrastBlack: 'AA',
    contrastWhite: '',
  },
  {
    title: 'grey-70',
    hex: '#676767',
    rgba: '38/38/38/0.7',
    contrastWhite: 'AA',
    contrastBlack: '',
  },
  {
    title: 'grey-80',
    hex: '#515151',
    rgba: '38/38/38/0.8',
    contrastWhite: 'AAA',
    contrastBlack: '',
    labels: ['font-grey'],
  },
  {
    title: 'grey-90',
    hex: '#3B3B3B',
    rgba: '38/38/38/0.9',
    contrastWhite: 'AAA',
    contrastBlack: '',
  },
];
