import {
  bookmark,
  bookmarkFilled,
  dashboard,
  dashboardColor,
  download,
  fullBattery,
  fullBatteryColor,
  han,
  informationCircle,
  informationCircleFilledColor,
  removeCircle,
  search,
  searchColor,
  upload,
  viewOn,
} from '@elvia/elvis-assets-icons';
import { addIcons } from '@elvia/elvis-icons';

addIcons({
  bookmark: { svg: bookmark.getIcon() },
  bookmarkFilled: { svg: bookmarkFilled.getIcon() },
  han: { svg: han.getIcon() },
  download: { svg: download.getIcon() },
  upload: { svg: upload.getIcon() },
  removeCircle: { svg: removeCircle.getIcon() },
  informationCircle: { svg: informationCircle.getIcon() },
  informationCircleFilledColor: { svg: informationCircleFilledColor.getIcon() },
  viewOn: { svg: viewOn.getIcon() },
  search: { svg: search.getIcon() },
  searchColor: { svg: searchColor.getIcon() },
  fullBattery: { svg: fullBattery.getIcon() },
  fullBatteryColor: { svg: fullBatteryColor.getIcon() },
  dashboard: { svg: dashboard.getIcon() },
  dashboardColor: { svg: dashboardColor.getIcon() },
});
