import * as fs from 'fs';
import * as gulp from 'gulp';
import { getThemeColorContrast, getThemeColor, ColorLabel } from '@elvia/elvis-colors';

/** All the possible labels that can be used as css variables for icon colors. */
export type IconLabels =
  | 'stroke'
  | 'filled-foreground'
  | 'filled-background'
  | 'filled-foreground-colored'
  | 'on'
  | 'caution'
  | 'warning'
  | 'error';
type ColorLabelContrast = `${ColorLabel}--contrast`;
type IconClassToThemeColor = {
  [key: string]: { [label in IconLabels]?: ColorLabel | ColorLabelContrast };
};
type IconLabelCssVariables = { [label in IconLabels]: ReturnType<typeof getThemeColor> };

/**
 * Creates css variables in the format: `--e-icon-color-{label}: var(--e-color-{color});`
 */
const iconLabelCssVariables: IconLabelCssVariables = {
  stroke: getThemeColor('text-primary'),
  'filled-foreground': getThemeColor('background-primary'),
  'filled-background': getThemeColor('text-primary'),
  'filled-foreground-colored': getThemeColor('static-black'),
  on: getThemeColor('state-on'),
  caution: getThemeColor('state-caution'),
  warning: getThemeColor('state-warning'),
  error: getThemeColor('state-error'),
};

/**
 * Used to set all the color css variables in an icon to the colors they should have.
 *
 * Stoke and 'filled-background' are set to the same color as the label, and the
 * 'filled-foreground' is set to the corresponding contrast color.
 */
const defaultLabeledIconWithContrast = (newClassName: ColorLabel): IconClassToThemeColor[string] => ({
  stroke: newClassName,
  'filled-background': newClassName,
  'filled-foreground': `${newClassName}--contrast`,
});

/**
 * Creates css classes in the format: `.e-icon--color-{label}` that set the color of the icon.
 * Different parts of the icon can be set to different colors.
 *
 * E.g. `.e-icon--color-on` sets the color of the icon that is labeled with stroke and 'filled-background' to the `state-on` color.
 */
const iconClassToThemeColor: IconClassToThemeColor = {
  inverted: {
    stroke: 'background-primary',
    'filled-foreground': 'text-primary',
    'filled-background': 'background-primary',
  },
  disabled: { stroke: 'state-disabled', 'filled-background': 'state-disabled' },
  placeholder: { stroke: 'text-placeholder', 'filled-background': 'text-placeholder' },
  on: defaultLabeledIconWithContrast('state-on'),
  green: defaultLabeledIconWithContrast('state-on'),
  caution: defaultLabeledIconWithContrast('state-caution'),
  yellow: defaultLabeledIconWithContrast('state-caution'),
  warning: defaultLabeledIconWithContrast('state-warning'),
  orange: defaultLabeledIconWithContrast('state-warning'),
  error: defaultLabeledIconWithContrast('state-error'),
  danger: defaultLabeledIconWithContrast('state-error'),
  red: defaultLabeledIconWithContrast('state-error'),
};

const WARNING = `// THIS FILE IS AUTOMATICALLY GENERATED AND WILL BE OVERWRITTEN.
// DO NOT MAKE CHANGES TO THIS FILE DIRECTLY.\n\n`;

const generateIconCssVariablesMap = () => {
  let fileContent = `$icon-variables: (\n`;
  for (const [label, color] of Object.entries(iconLabelCssVariables)) {
    fileContent += `\t'${label}': ${color},\n`;
  }
  fileContent += `);\n\n`;

  return fileContent;
};

const isContrastColor = (color: ColorLabel | ColorLabelContrast): color is ColorLabelContrast =>
  typeof color === 'string' && color.endsWith('--contrast');

const getScssColors = (colors: IconClassToThemeColor[string]) => {
  let scssColors = '';
  for (const [label, color] of Object.entries(colors)) {
    if (isContrastColor(color)) {
      scssColors += `'${label}': ${getThemeColorContrast(color.replace('--contrast', '') as ColorLabel)}, `;
    } else {
      scssColors += `'${label}': ${getThemeColor(color)}, `;
    }
  }
  return scssColors;
};

const generateIconColorClassesMap = () => {
  let fileContent = `$icon-theme-classes: (\n`;
  for (const [label, colors] of Object.entries(iconClassToThemeColor)) {
    if (label === 'inverted') {
      fileContent += `\t'${label}': ( ${getScssColors(colors)} ),\n`;
    } else {
      fileContent += `\t'color-${label}': ( ${getScssColors(colors)} ),\n`;
    }
  }
  fileContent += `);\n\n`;

  return fileContent;
};

const writeIconThemeVariables = async () => {
  let fileContent = WARNING;
  fileContent += generateIconCssVariablesMap();
  fileContent += generateIconColorClassesMap();
  fs.writeFileSync('./dist/scss/themeVariables.scss', fileContent);
  return true;
};

const makeDistFolder = async () => {
  const dir = './dist/scss';
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  return true;
};

const generateIconsScss = gulp.series(makeDistFolder, writeIconThemeVariables);

export { generateIconsScss };
