import { Color } from './color.interface';

export const primaryColors: Color[] = [
    {
        title: 'white',
        labels: ['elvia-on'],
        hex: '#FFFFFF',
        rgba: '255 / 255 / 255',
        textColorBlack: true,
        contrast: 'AAA',
        lg: true,
    },
    {
        title: 'green',
        labels: ['elvia-charge'],
        hex: '#29D305',
        rgba: '41 / 211 / 5',
        textColorBlack: true,
        contrast: 'AAA',
        lg: true,
    },
    {
        title: 'black',
        labels: ['elvia-off', 'font-color'],
        hex: '#000000',
        rgba: '0 / 0 / 0',
        textColorBlack: false,
        contrast: 'AAA',
        lg: true,
    },
    {
        title: 'grey',
        hex: '#262626',
        rgba: '38 / 38 / 38',
        textColorBlack: false,
        contrast: 'AAA',
        lg: true,
    },
];
export const signalColors: Color[] = [
    {
        title: 'yellow',
        hex: '#FFFF00',
        rgba: '255 / 255 / 0',
        textColorBlack: true,
        contrast: 'AAA',
    },
    {
        title: 'orange',
        hex: '#FFA000',
        rgba: '255 / 160 / 0',
        textColorBlack: true,
        contrast: 'AAA',
    },
    {
        title: 'red',
        hex: '#FF0000',
        rgba: '255 / 0 / 0',
        textColorBlack: true,
        contrast: 'AA',
    },
];
export const dataColors: Color[] = [
    {
        title: 'green-apple',
        titleWithSpace: 'green apple',
        hex: '#21AC04',
        rgba: '33 / 172 / 4',
        textColorBlack: true,
        contrast: 'AA',
    },
    {
        title: 'violet-grape',
        titleWithSpace: 'violet grape',
        hex: '#490192',
        rgba: '73 / 1 / 146',
        textColorBlack: false,
        contrast: 'AAA',
    },
    {
        title: 'blue-berry',
        titleWithSpace: 'blue berry',
        hex: '#006DDB',
        rgba: '0 / 109 / 219',
        textColorBlack: false,
        contrast: 'AA',
    },
    {
        title: 'purple-plum',
        titleWithSpace: 'purple plum',
        hex: '#B66DFF',
        rgba: '182 / 109 / 255',
        textColorBlack: true,
        contrast: 'AA',
    },
    {
        title: 'orange-mango',
        titleWithSpace: 'orange mango',
        hex: '#DB6D00',
        rgba: '219 / 109 / 0',
        textColorBlack: true,
        contrast: 'AA',
    },
    {
        title: 'red-tomato',
        titleWithSpace: 'red tomato',
        hex: '#B90202',
        rgba: '185 / 2 / 2',
        textColorBlack: false,
        contrast: 'AAA',
    },
];
export const greysColors: Color[] = [
    {
        title: 'grey-02',
        hex: '#FAFAFA',
        rgba: '38/38/38/0.02',
        textColorBlack: true,
        contrast: 'AAA',
    },
    {
        title: 'grey-05',
        hex: '#F4F4F4',
        rgba: '38/38/38/0.05',
        textColorBlack: true,
        contrast: 'AAA',
        labels: ['disabled-light'],
    },
    {
        title: 'grey-10',
        hex: '#E9E9E9',
        rgba: '38/38/38/0.1',
        textColorBlack: true,
        contrast: 'AAA',
    },
    {
        title: 'grey-20',
        hex: '#D3D3D3',
        rgba: '38/38/38/0.2',
        textColorBlack: true,
        contrast: 'AAA',
    },
    {
        title: 'grey-30',
        hex: '#BDBDBD',
        rgba: '38/38/38/0.3',
        textColorBlack: true,
        contrast: 'AAA',
        labels: ['disabled'],
    },
    {
        title: 'grey-40',
        hex: '#A8A8A8',
        rgba: '38/38/38/0.4',
        textColorBlack: true,
        contrast: 'AAA',
    },
    {
        title: 'grey-50',
        hex: '#929292',
        rgba: '38/38/38/0.5',
        textColorBlack: true,
        contrast: 'AA',
    },
    {
        title: 'grey-60',
        hex: '#7C7C7C',
        rgba: '38/38/38/0.6',
        textColorBlack: true,
        contrast: 'AA',
    },
    {
        title: 'grey-70',
        hex: '#676767',
        rgba: '38/38/38/0.7',
        textColorBlack: false,
        contrast: 'AA',
    },
    {
        title: 'grey-80',
        hex: '#515151',
        rgba: '38/38/38/0.8',
        textColorBlack: false,
        contrast: 'AAA',
        labels: ['font-grey'],
    },
    {
        title: 'grey-90',
        hex: '#3B3B3B',
        rgba: '38/38/38/0.9',
        textColorBlack: false,
        contrast: 'AAA',
    },
];

