name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Install
        run: npm install
      - name: Percy Test
        uses: percy/exec-action@v0.3.0
        with:
          command: 'npm run percy'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
